trigger:
- main

variables:
  DOCKER_IMAGE: "sharmila79/dummy-maven-project"
  DOCKER_CREDENTIALS_ID: "docker-id"
  KUBECONFIG_CREDENTIALS_ID: "kubernetes-id"

pool:
  name: Default
  demands:
  - agent.name -equals sqtask


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


