trigger:
- main

variables:
  DOCKER_IMAGE: "sharmila79/Django-project"
  DOCKER_CREDENTIALS_ID: "docker-id"
  KUBECONFIG_CREDENTIALS_ID: "kubernetes-id"

pool:
  name: Default
  demands:
  - agent.name -equals sqtaskagentpool

stages:
- stage: CloneCode
  jobs:
  - job: CloneCode
    steps:
    - checkout: self
      clean: true

