trigger:
- main

variables:
  DOCKER_IMAGE: "sharmila79/dummy-maven-project"
  DOCKER_CREDENTIALS_ID: "docker-id"
  KUBECONFIG_CREDENTIALS_ID: "kubernetes-id"

pool:
  name: Default
  demands:
  - agent.name -equals sqtask

stages:
- stage: CloneCode
  jobs:
  - job: CheckoutRepo
    steps:
    - checkout: self
    - script: echo "Repository cloned successfully!"
      displayName: 'Clone Repository'

- stage: RunScript
  jobs:
  - job: RunOneLineScript
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'